# Generated by Django 5.2.3 on 2025-06-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_image_brand_name_ar_alter_brand_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='body',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name (English)'),
        ),
    ]
